# Generated by Django 5.0.1 on 2024-01-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(default='somestring'),
        ),
    ]
